# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nav/ROSdata.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ROSdata(genpy.Message):
  _md5sum = "dfeef41f7b4427e94c0ce4d2ec551822"
  _type = "nav/ROSdata"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 yaw
float32 pitch
float32 dis
bool is_aimed
bool is_target_exists
"""
  __slots__ = ['yaw','pitch','dis','is_aimed','is_target_exists']
  _slot_types = ['float32','float32','float32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       yaw,pitch,dis,is_aimed,is_target_exists

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ROSdata, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.yaw is None:
        self.yaw = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.dis is None:
        self.dis = 0.
      if self.is_aimed is None:
        self.is_aimed = False
      if self.is_target_exists is None:
        self.is_target_exists = False
    else:
      self.yaw = 0.
      self.pitch = 0.
      self.dis = 0.
      self.is_aimed = False
      self.is_target_exists = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3f2B().pack(_x.yaw, _x.pitch, _x.dis, _x.is_aimed, _x.is_target_exists))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.yaw, _x.pitch, _x.dis, _x.is_aimed, _x.is_target_exists,) = _get_struct_3f2B().unpack(str[start:end])
      self.is_aimed = bool(self.is_aimed)
      self.is_target_exists = bool(self.is_target_exists)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3f2B().pack(_x.yaw, _x.pitch, _x.dis, _x.is_aimed, _x.is_target_exists))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.yaw, _x.pitch, _x.dis, _x.is_aimed, _x.is_target_exists,) = _get_struct_3f2B().unpack(str[start:end])
      self.is_aimed = bool(self.is_aimed)
      self.is_target_exists = bool(self.is_target_exists)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f2B = None
def _get_struct_3f2B():
    global _struct_3f2B
    if _struct_3f2B is None:
        _struct_3f2B = struct.Struct("<3f2B")
    return _struct_3f2B
