// Generated by gencpp from file bluesea2/ControlRequest.msg
// DO NOT EDIT!


#ifndef BLUESEA2_MESSAGE_CONTROLREQUEST_H
#define BLUESEA2_MESSAGE_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluesea2
{
template <class ContainerAllocator>
struct ControlRequest_
{
  typedef ControlRequest_<ContainerAllocator> Type;

  ControlRequest_()
    : index(0)  {
    }
  ControlRequest_(const ContainerAllocator& _alloc)
    : index(0)  {
  (void)_alloc;
    }



   typedef int64_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::bluesea2::ControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluesea2::ControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlRequest_

typedef ::bluesea2::ControlRequest_<std::allocator<void> > ControlRequest;

typedef boost::shared_ptr< ::bluesea2::ControlRequest > ControlRequestPtr;
typedef boost::shared_ptr< ::bluesea2::ControlRequest const> ControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluesea2::ControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluesea2::ControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluesea2::ControlRequest_<ContainerAllocator1> & lhs, const ::bluesea2::ControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluesea2::ControlRequest_<ContainerAllocator1> & lhs, const ::bluesea2::ControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluesea2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluesea2::ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluesea2::ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a92c772b35d41f76733d8eb9779b0e1";
  }

  static const char* value(const ::bluesea2::ControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a92c772b35d41f7ULL;
  static const uint64_t static_value2 = 0x6733d8eb9779b0e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluesea2/ControlRequest";
  }

  static const char* value(const ::bluesea2::ControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 index\n"
;
  }

  static const char* value(const ::bluesea2::ControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluesea2::ControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluesea2::ControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluesea2::ControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int64_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUESEA2_MESSAGE_CONTROLREQUEST_H
