// Generated by gencpp from file bluesea2/Control.msg
// DO NOT EDIT!


#ifndef BLUESEA2_MESSAGE_CONTROL_H
#define BLUESEA2_MESSAGE_CONTROL_H

#include <ros/service_traits.h>


#include <bluesea2/ControlRequest.h>
#include <bluesea2/ControlResponse.h>


namespace bluesea2
{

struct Control
{

typedef ControlRequest Request;
typedef ControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Control
} // namespace bluesea2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bluesea2::Control > {
  static const char* value()
  {
    return "6a92c772b35d41f76733d8eb9779b0e1";
  }

  static const char* value(const ::bluesea2::Control&) { return value(); }
};

template<>
struct DataType< ::bluesea2::Control > {
  static const char* value()
  {
    return "bluesea2/Control";
  }

  static const char* value(const ::bluesea2::Control&) { return value(); }
};


// service_traits::MD5Sum< ::bluesea2::ControlRequest> should match
// service_traits::MD5Sum< ::bluesea2::Control >
template<>
struct MD5Sum< ::bluesea2::ControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bluesea2::Control >::value();
  }
  static const char* value(const ::bluesea2::ControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluesea2::ControlRequest> should match
// service_traits::DataType< ::bluesea2::Control >
template<>
struct DataType< ::bluesea2::ControlRequest>
{
  static const char* value()
  {
    return DataType< ::bluesea2::Control >::value();
  }
  static const char* value(const ::bluesea2::ControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bluesea2::ControlResponse> should match
// service_traits::MD5Sum< ::bluesea2::Control >
template<>
struct MD5Sum< ::bluesea2::ControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bluesea2::Control >::value();
  }
  static const char* value(const ::bluesea2::ControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluesea2::ControlResponse> should match
// service_traits::DataType< ::bluesea2::Control >
template<>
struct DataType< ::bluesea2::ControlResponse>
{
  static const char* value()
  {
    return DataType< ::bluesea2::Control >::value();
  }
  static const char* value(const ::bluesea2::ControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BLUESEA2_MESSAGE_CONTROL_H
