// Generated by gencpp from file bluesea2/DefenceZoneResponse.msg
// DO NOT EDIT!


#ifndef BLUESEA2_MESSAGE_DEFENCEZONERESPONSE_H
#define BLUESEA2_MESSAGE_DEFENCEZONERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluesea2
{
template <class ContainerAllocator>
struct DefenceZoneResponse_
{
  typedef DefenceZoneResponse_<ContainerAllocator> Type;

  DefenceZoneResponse_()
    {
    }
  DefenceZoneResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DefenceZoneResponse_

typedef ::bluesea2::DefenceZoneResponse_<std::allocator<void> > DefenceZoneResponse;

typedef boost::shared_ptr< ::bluesea2::DefenceZoneResponse > DefenceZoneResponsePtr;
typedef boost::shared_ptr< ::bluesea2::DefenceZoneResponse const> DefenceZoneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluesea2::DefenceZoneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace bluesea2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::bluesea2::DefenceZoneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluesea2/DefenceZoneResponse";
  }

  static const char* value(const ::bluesea2::DefenceZoneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::bluesea2::DefenceZoneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DefenceZoneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluesea2::DefenceZoneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::bluesea2::DefenceZoneResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BLUESEA2_MESSAGE_DEFENCEZONERESPONSE_H
