// Generated by gencpp from file bluesea2/DefenceZoneRequest.msg
// DO NOT EDIT!


#ifndef BLUESEA2_MESSAGE_DEFENCEZONEREQUEST_H
#define BLUESEA2_MESSAGE_DEFENCEZONEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluesea2
{
template <class ContainerAllocator>
struct DefenceZoneRequest_
{
  typedef DefenceZoneRequest_<ContainerAllocator> Type;

  DefenceZoneRequest_()
    : index(0)
    , ip()  {
    }
  DefenceZoneRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , ip(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ip_type;
  _ip_type ip;





  typedef boost::shared_ptr< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DefenceZoneRequest_

typedef ::bluesea2::DefenceZoneRequest_<std::allocator<void> > DefenceZoneRequest;

typedef boost::shared_ptr< ::bluesea2::DefenceZoneRequest > DefenceZoneRequestPtr;
typedef boost::shared_ptr< ::bluesea2::DefenceZoneRequest const> DefenceZoneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluesea2::DefenceZoneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluesea2::DefenceZoneRequest_<ContainerAllocator1> & lhs, const ::bluesea2::DefenceZoneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.ip == rhs.ip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluesea2::DefenceZoneRequest_<ContainerAllocator1> & lhs, const ::bluesea2::DefenceZoneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluesea2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e59dcc27f1124e7929b888c8823d5573";
  }

  static const char* value(const ::bluesea2::DefenceZoneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe59dcc27f1124e79ULL;
  static const uint64_t static_value2 = 0x29b888c8823d5573ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluesea2/DefenceZoneRequest";
  }

  static const char* value(const ::bluesea2::DefenceZoneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n"
"string ip\n"
;
  }

  static const char* value(const ::bluesea2::DefenceZoneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DefenceZoneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluesea2::DefenceZoneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluesea2::DefenceZoneRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUESEA2_MESSAGE_DEFENCEZONEREQUEST_H
