// Generated by gencpp from file bluesea2/DefenceZone.msg
// DO NOT EDIT!


#ifndef BLUESEA2_MESSAGE_DEFENCEZONE_H
#define BLUESEA2_MESSAGE_DEFENCEZONE_H

#include <ros/service_traits.h>


#include <bluesea2/DefenceZoneRequest.h>
#include <bluesea2/DefenceZoneResponse.h>


namespace bluesea2
{

struct DefenceZone
{

typedef DefenceZoneRequest Request;
typedef DefenceZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DefenceZone
} // namespace bluesea2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bluesea2::DefenceZone > {
  static const char* value()
  {
    return "e59dcc27f1124e7929b888c8823d5573";
  }

  static const char* value(const ::bluesea2::DefenceZone&) { return value(); }
};

template<>
struct DataType< ::bluesea2::DefenceZone > {
  static const char* value()
  {
    return "bluesea2/DefenceZone";
  }

  static const char* value(const ::bluesea2::DefenceZone&) { return value(); }
};


// service_traits::MD5Sum< ::bluesea2::DefenceZoneRequest> should match
// service_traits::MD5Sum< ::bluesea2::DefenceZone >
template<>
struct MD5Sum< ::bluesea2::DefenceZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bluesea2::DefenceZone >::value();
  }
  static const char* value(const ::bluesea2::DefenceZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluesea2::DefenceZoneRequest> should match
// service_traits::DataType< ::bluesea2::DefenceZone >
template<>
struct DataType< ::bluesea2::DefenceZoneRequest>
{
  static const char* value()
  {
    return DataType< ::bluesea2::DefenceZone >::value();
  }
  static const char* value(const ::bluesea2::DefenceZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bluesea2::DefenceZoneResponse> should match
// service_traits::MD5Sum< ::bluesea2::DefenceZone >
template<>
struct MD5Sum< ::bluesea2::DefenceZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bluesea2::DefenceZone >::value();
  }
  static const char* value(const ::bluesea2::DefenceZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluesea2::DefenceZoneResponse> should match
// service_traits::DataType< ::bluesea2::DefenceZone >
template<>
struct DataType< ::bluesea2::DefenceZoneResponse>
{
  static const char* value()
  {
    return DataType< ::bluesea2::DefenceZone >::value();
  }
  static const char* value(const ::bluesea2::DefenceZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BLUESEA2_MESSAGE_DEFENCEZONE_H
